---
# INSTALL NAGIOS
  - name: install nagios for Ubuntu
    apt:
      name:
        - nagios4-core
        - nagios-plugins
      state: latest

# INSTALL ELSTACK
  - name: Install necessary prerequisites
    apt:
      name:
        - default-jre
        - apt-transport-https
        - curl
        - software-properties-common
      state: latest
    become: yes

  - name: Add Elasticsearch GPG key
    apt_key:
      url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    become: yes

  - name: Add Elasticsearch APT repository
    apt_repository:
      repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
      state: present
    become: yes

  - name: Install Elasticsearch
    apt:
      name: elasticsearch
      state: latest

  - name: Install Kibana
    apt:
      name: kibana
      state: latest

  - name: Install Logstash
    apt:
      name: logstash
      state: latest

# INSTALL Lampstack
  - name: install apache2 and php packages for Ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest

  - name: install mariadb package Ubuntu
    apt:
      name: mariadb-server
      state: latest

  - name: "Mariadb- Restarting/Enabling"
    service:
      name: mariadb
      state: restarted
      enabled: true

# install PROMETHEUS
  - name: Install Prometheus for Ubuntu
    apt:
      name: prometheus
      state: latest

  - name: Prometheus Start service
    service:
      name: prometheus
      state: restarted
      enabled: true

# install GRAFANA
  - name: Install dependencies
    apt:
      name:
        - software-properties-common
        - apt-transport-https
        - ca-certificates
        - curl
    tags: [prerequisites]

  - name: Add Grafana APT repository key
    apt_key:
      url: https://packages.grafana.com/gpg.key
      state: present
    tags: [prerequisites]

  - name: Add Grafana APT repository
    apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main
      state: present

  - name: Install Grafana
    apt:
      name: grafana
      state: present

  - name: Start and enable Grafana service
    systemd:
      name: grafana-server
      state: started
      enabled: yes

#INSTALL INFLUXDB
  - name: Installing dependencies
    apt:
      name:
        - apt-transport-https
        - software-properties-common
        - wget
      state: latest


  - name: Adding Influxdb in the repository
    shell: |
      wget -q https://repos.influxdata.com/influxdb.key
      sleep 5
      echo '23a1c8836f0afc5ed24e0486339d7cc8f6790b83886c4c96995b88a061c5bb5d influxdb.key' | sha256sum -c && cat influxdb.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/influxdb.gpg > /dev/null
      sleep 5
      echo 'deb [signed-by=/etc/apt/trusted.gpg.d/influxdb.gpg] https://repos.influxdata.com/debian stable main' | sudo tee /etc/apt/sources.list.d/influxdata.list

  - name: Installing Influxdb
    apt:
      name:
        - influxdb

  - name: Making sure that the Influxd is enabled and started
    service:
      name: influxdb
      state: started
      enabled: true
